void head(char mas[]);
void yellow();
void white();
void red();
void green();
int Len(int ch);
bool lucky_number(int ch);
int new_number(int ch);
int best_m(double* p);
void salary(double* p, double *z, int l);
void count_s(int &doh, int &opozd, int &string);
void count_o(int &doh, int &opozd, int &string);
void count_d(int &doh, int &opozd, int &string);
int d_ch(int n, int k);
int r_ch(int n, int k);
void rand_arr(int*arr, int r);
void print_arr(int*arr, int r);
void clear_ch(int*arr, int r);
void without(int ch);
void tr(int a);
